### ISSUE TITLE
converting svd scores to weights. scheme H

### ISSUE THREAD

**Issue by j-chou** [hyaduvanshi/quartetstotree#2]
Shashank and I were talking about the svd scores to weights conversion, and shashank suggested the following scheme:
Let R=1/e^(svd_max-svd_med). Then weight(q)=e^(R*(1-svd_score/svd_overall_max))
where svd_overall_max is the global maximum svd score. 
This will fix problems with svd_min = 0 and prevent the weights from being too large or too small. Let's call this new scheme H. In the python file we will need a list of all svd scores and compute the max of this list before assigning any weights to the quartets.

**Comment by redavids** [comment]
Thank you for posting this to the github.  Can you help me understand why
svd_min does not appear anywhere in this function?  If we have good data we
should expect svd_min= 0 to appear according to the theory.

On Fri, Apr 10, 2015 at 5:14 PM, j-chou <notifications@github.com> wrote:

> Shashank and I were talking about the svd scores to weights conversion,
> and shashank suggested the following scheme:
> Let R=1/e^(svd_max-svd_med). Then
> weight(q)=e^(R*(1-svd_score/svd_overall_max))
> where svd_overall_max is the global maximum svd score.
> This will fix problems with svd_min = 0 and prevent the weights from being
> too large or too small. Let's call this new scheme H. In the python file we
> will need a list of all svd scores and compute the max of this list before
> assigning any weights to the quartets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyaduvanshi/quartetstotree/issues/2>.
>



-- 
Ruth Davidson
Department of Mathematics, University of Illinois Urbana-Champaign
http://www.math.uiuc.edu/~redavid2/
